import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium,webkit} from 'playwright';
const BASE=process.env.BASE||'http://127.0.0.1:4176';const src=fs.readFileSync('/home/ubuntu/studyBridge/audit_reports/learningmate_ec2_e2e_20260924T142154Z/tools/browser_race.js','utf8');const creds={email:src.match(/const EMAIL = '([^']+)'/)[1],password:src.match(/const PW = '([^']+)'/)[1]};const results=[];
for(const [engine,width,type] of [[chromium,1280,'GENERAL'],[chromium,393,'CAM'],[webkit,393,'GENERAL'],[webkit,430,'CAM']]){
 const browser=await engine.launch(engine===chromium?{args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']}:{});const ctx=await browser.newContext({viewport:{width,height:900},ignoreHTTPSErrors:true,...(engine===chromium?{permissions:['camera','microphone']}:{})});const page=await ctx.newPage();page.on('dialog',d=>d.accept());let groupId;const name='QA TIMER '+type+' '+Date.now();
 const api=(path,method='GET',body)=>page.evaluate(async({path,method,body})=>{const r=await fetch(path,{method,headers:{Authorization:'Bearer '+localStorage.token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json().catch(()=>null)};},{path,method,body});
 const rec=(name,data={})=>{results.push({engine:engine.name(),width,type,name,...data});console.log(engine.name(),width,type,name,JSON.stringify(data));};
 try{
 await page.goto(BASE+'/login');await page.locator('[name=email]').fill(creds.email);await page.locator('[name=password]').fill(creds.password);await page.locator('[type=submit]').click();await page.waitForURL(u=>!u.pathname.endsWith('/login'));
 groupId=await page.evaluate(async({name,type})=>{const fd=new FormData();const d=new Date();for(const[k,v]of Object.entries({title:name,description:'자동 QA 후 삭제',hashtags:'qa',startDate:d.toISOString().slice(0,10),endDate:new Date(+d+86400000*2).toISOString().slice(0,10),capacity:2,isPublic:true,studyType:type,targetStudyMinutes:240,joinQuestionEnabled:false,nicknameRuleEnabled:false}))fd.append(k,String(v));const r=await fetch('/api/groups',{method:'POST',headers:{Authorization:'Bearer '+localStorage.token},body:fd});const j=await r.json();if(!r.ok)throw Error('create '+r.status);return j.id||j.groupId;},{name,type});
 const enter=async()=>{await page.goto(BASE+'/groupstudy');await page.getByText(name,{exact:true}).first().click();await page.getByRole('button',{name:'스터디 입장',exact:true}).click();await page.getByRole('button',{name:'입장',exact:true}).last().click();await page.getByRole('button',{name:'확인',exact:true}).last().click();await page.locator('[data-testid=room-timer][data-active=true]').waitFor({timeout:20000});};
 await enter();const current=await api('/api/timers/current');assert.equal(current.status,200);const session=current.data.id;
 const start=await page.getByTestId('room-timer-value').innerText();await page.waitForTimeout(2100);const advanced=await page.getByTestId('room-timer-value').innerText();assert.notEqual(start,advanced);
 const box=await page.getByTestId('room-timer').boundingBox();assert.ok(box&&box.x>=0&&box.x+box.width<=width);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);rec('mounted/visible/ticking PASS',{session});
 await page.reload();const restored=await api('/api/timers/current');assert.equal(restored.data.id,session);await enter();assert.notEqual(await page.getByTestId('room-timer-value').innerText(),'00:00:00');rec('refresh/re-entry restores same session PASS');

 // A second browser tab uses the same authenticated server sync contract.
 const second=await ctx.newPage();await second.goto(BASE+'/');
 const again=await second.evaluate(async(groupId)=>{const r=await fetch(`/api/timers/sync/${groupId}?heartbeat=true`,{method:'POST',headers:{Authorization:'Bearer '+localStorage.token}});if(!r.ok)throw Error('second tab sync '+r.status);return r.json();},groupId);assert.equal(again.id,session);await second.close();rec('same-user second tab same session PASS');
 await api('/api/timers/heartbeat','POST');const before=await api(`/api/groups/${groupId}/stats/study-time`);assert.equal(before.status,200);
 const leave=width<769?page.locator('.room-mobile-leave'):page.locator('.room-header').getByRole('button',{name:'나가기',exact:true});await leave.click();await page.getByTestId('room-timer').waitFor({state:'detached'});const ended=await api('/api/timers/current');assert.ok(!ended.data?.startTime||ended.data.endTime);const after=await api(`/api/groups/${groupId}/stats/study-time`);assert.equal(after.status,200);assert.ok(after.data.my.studySeconds>0);assert.ok(after.data.my.studySeconds>=before.data.my.studySeconds);assert.equal(after.data.my.activeNow,false);assert.equal(after.data.my.sessionCount,1);rec('end/stats HTTP PASS',{before:before.data,after:after.data});
 }catch(e){rec('FAIL',{error:e.message.slice(0,250)});}finally{if(groupId){await api('/api/timers/end','POST',{reason:'QA_CLEANUP'});await api(`/api/groups/${groupId}`,'DELETE');}await browser.close();}
}
fs.writeFileSync('audit_reports/final-addon-2/timer.json',JSON.stringify(results,null,2));if(results.some(x=>x.name==='FAIL'))process.exitCode=1;
