package com.studybridge.api.entity;

/**
 * 학습 왕복 루프(Learning Loop) 이벤트 타입.
 * 모든 AI/학습 행동을 추적해 다음 AI 호출의 컨텍스트로 재사용하기 위한 표준값.
 */
public enum LearningEventType {
    MATERIAL_UPLOADED,
    MATERIAL_SUMMARY_GENERATED,
    MATERIAL_ROADMAP_GENERATED,
    MATERIAL_QUIZ_GENERATED,
    QUIZ_SUBMITTED,
    QUIZ_WRONG_ANSWERED,
    WRONG_NOTE_CREATED,
    SIMILAR_QUESTION_GENERATED,
    AI_EXPLANATION_GENERATED,
    REVIEW_SCHEDULE_RECOMMENDED,
    PLANNER_REVIEW_CREATED,
    STUDY_LOG_CREATED,
    AI_CHAT_ASKED,
    AI_CHAT_ANSWERED,
    AGENT_FIRST_ANSWER,
    AGENT_VALIDATION,
    AGENT_PEER_FEEDBACK,
    USER_FEEDBACK_SAVED
}
